apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-default-deny.yaml
  - allow-dns-egress.yaml
  - allow-core-ingress-from-ui-ai-edge.yaml
  - allow-ai-core-edge-ui-zone-flows.yaml
